using UnityEngine;

public class platformmovement : MonoBehaviour
{
    public float speed;
    public int startingpoint;
    public Transform[] points;
    private int i;


    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        transform.position = points[startingpoint].position;
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        if(Vector3.Distance(transform.position, points[i].position) < 0.02f)
        {
           i++;
           if(i == points.Length) 
           {
             i = 0;
           }
        }
        transform.position = Vector3.MoveTowards(transform.position, points[i].position, speed * Time.deltaTime);
    }

    private void OnCollisionEnter(Collision collision)
    {
        collision.transform.SetParent(transform);
    }

    private void OnCollisionExit(Collision collision)
    {
        collision.transform.SetParent(null);
    }

    private void OnTriggerEnter(Collider other)
    {
        other.transform.SetParent(transform);
    }
        
    private void OnTriggerExit(Collider other)
    {
        other.transform.SetParent(null);
    }
}
